---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Morra Cinese
description: Crea la tua 'Morra Cinese'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: codeclub, python
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Turno del Giocatore
  - 
    title: Turno del Computer
  - 
    title: Controlla il Risultato
  - 
    title: 'Sfida: Arte ASCII'
  - 
    title: 'Sfida: Crea un nuovo gioco'
